<?php

/**
 * WPLite Framework Autoloader
 * 
 * Generated by WPLite CLI for namespace: Forooshyar\WPLite
 * 
 * @generated Do not edit this file directly. Run `php wplite build` to regenerate.
 */

// PSR-4 Autoloader for Forooshyar\WPLite
spl_autoload_register(function ($class) {
    $prefix = 'Forooshyar\\WPLite\\';
    $baseDir = __DIR__ . '/';

    $len = strlen($prefix);
    if (strncmp($prefix, $class, $len) !== 0) {
        return;
    }

    $relativeClass = substr($class, $len);
    $file = $baseDir . str_replace('\\', '/', $relativeClass) . '.php';

    if (file_exists($file)) {
        require $file;
    }
});

// Load helper functions
foreach (glob(__DIR__ . '/Helpers/*.php') as $file) {
    require_once $file;
}
